# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false 

# Setup
title:            ddan's blog
tagline:          'ddanddan18'
description:      '즐거움의 공간' 
url:              "https://ddanddan18.github.io/"
baseurl:          ""

author:
  name:           'DDanddan Jo'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ddanddan18/

gems: [jekyll-paginate]
#paginate: 5
#paginate_path: "page:num"
